model:
  model_id: game_rft
  sample_size: 8
  channels: 128

  n_layers: 36
  n_heads: 20
  d_model: 2560

  tokens_per_frame: 64
  n_buttons: 11
  n_mouse_axes: 2

  cfg_prob: 0.1
  n_frames: 1536

  causal: true
  uncond: false
  backbone: dit
  has_audio: false
  rope_impl: motion
  rope_ats_delta: 2.0

  local_window: 16
  global_window: null  # full window

  gradient_checkpointing: true

train:
  trainer_id: rft
  data_id: sequence_packing
  data_kwargs:
    window_length: 1536
    dataset_path: /mnt/data/lapp0/BlackOpsColdWar/train_npy
    batch_columns: ["depth_latent", "mouse", "buttons"]

  sample_data_id: cod
  sample_data_kwargs:
    window_length: 60  # size of single ground truth start tokens
    dataset_path: /mnt/data/lapp0/BlackOpsColdWar/train_npy
    batch_columns: ["depth_latent", "mouse", "buttons"]

  target_batch_size: 16
  batch_size: 1

  epochs: 10000

  opt: Muon
  opt_kwargs:
    lr: 1.0e-3
    momentum: 0.95
    adamw_lr: 1.0e-4
    adamw_wd: 1.0e-4
    adamw_eps: 1.0e-15
    adamw_betas: [0.9, 0.95]
    adamw_keys: [core.proj_in, core.proj_out.proj, core.t_embed, core.control_embed, gate, adaln]

  scheduler: null

  checkpoint_dir: checkpoints/video_dit_v4_5B
  output_path: /mnt/data/owl-wms/checkpoints/dit_v4_5B
  resume_ckpt: null

  sample_interval: 5000
  save_interval: 5000

  sampler_id: av_caching
  sampler_kwargs:
    n_steps: 16
    cfg_scale: 1.0
    num_frames: 900
    noise_prev: 0.2
    only_return_generated: false

  n_samples: 4
  eval_sample_dir: null

  vae_id: null
  vae_batch_size: 4

  vae_scale: 0.63
  vae_cfg_path: /mnt/data/shahbuland/owl-vaes/configs/cod_yt_v2/base.yml
  vae_ckpt_path: /mnt/data/checkpoints/owl_vaes/cod_yt_v2/cod_yt_v2_515k_ema_decoder.pt

wandb:
  name: louiscastricato
  project: video_models
  run_name: video_dit_v4_5B
